# SPDX-FileCopyrightText: Copyright Contributors to the GXF project
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
data:
  broker.xml: |
    <configuration xmlns="urn:activemq" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:activemq /schema/artemis-configuration.xsd">
      <core xmlns="urn:activemq:core" xsi:schemaLocation="urn:activemq:core ">
        
        {{- range $parameter, $value := $.Values.brokerConfiguration.parameters }}
          <{{ $parameter }}>{{ $value }}</{{ $parameter }}>
        {{- end }}
        
        <address-settings>
          {{- range $address, $properties := $.Values.brokerConfiguration.addresses }}
          <address-setting match={{ $address | quote }}>
            {{- range $property, $value := $properties }}
            <{{ $property }}>{{ $value }}</{{ $property }}>
            {{- end }}
          </address-setting>
          {{- end }}
        </address-settings>
        
        <addresses>
          <address name="DLQ">
            <anycast>
              <queue name="DLQ"/>
            </anycast>
          </address>
          <address name="ExpiryQueue">
            <anycast>
              <queue name="ExpiryQueue"/>
            </anycast>
          </address>
        </addresses>
        
        <connectors>
          <connector name="netty-connector">tcp://0.0.0.0:61617</connector>
        </connectors>
        
        <connection-ttl-override>300000</connection-ttl-override>

        <!-- Acceptors -->
        <acceptors>
          {{- if .Values.ssl.enabled }}
          <acceptor name="netty-ssl-acceptor">tcp://0.0.0.0:61617?sslEnabled=true;keyStorePath=/var/lib/artemis-instance/ssl/broker.ks;keyStorePassword=${keyStorePassword};trustStorePath=/var/lib/artemis-instance/ssl/client.ts;trustStorePassword=${trustStorePassword};needClientAuth=true;enabledProtocols=TLSv1,TLSv1.1,TLSv1.2</acceptor>
          {{- else }}
          <acceptor name="netty-ssl-acceptor">tcp://0.0.0.0:61617</acceptor>
          {{- end }}
        </acceptors>
        
      </core>
      
    </configuration>
