{{if .Values.authentication.defaultUser.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  artemis-password: {{ "simetraehcapa" | b64enc }}
  artemis-username: {{ "artemis" | b64enc }}
{{end}}
