# SPDX-FileCopyrightText: Copyright Contributors to the GXF project
#
# SPDX-License-Identifier: Apache-2.0

{{if .Values.artemis.useDefaultUser}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.artemis.defaultUser.artemisPassword }}
  artemis-password:  {{ .Values.artemis.defaultUser.artemisPassword | b64enc | quote }}
  {{ else }}
  artemis-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  artemis-username: {{.Values.artemis.defaultUser.artemisUser}}
{{end}}