# SPDX-FileCopyrightText: Copyright Contributors to the GXF project
#
# SPDX-License-Identifier: Apache-2.0

{{ if ne (include "service-account" .) "default" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "service-account" . }}
  labels:
    app: {{ template "service-account" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{ end }}
