# SPDX-FileCopyrightText: Copyright Contributors to the GXF project
#
# SPDX-License-Identifier: Apache-2.0

helm-extra-args: --timeout 600s
# check-version-increment: true
debug: true
target-branch: main