# SPDX-FileCopyrightText: Copyright Contributors to the GXF project
#
# SPDX-License-Identifier: Apache-2.0

## activemq-artemis image version
## ref: https://hub.docker.com/r/vromero/activemq-artemis/tags
##
imageRepo: ""
image: apache/activemq-artemis
imageTag: latest

## Create a database user
## When the default user is set to true, the user in the secrets.yaml will be used
## Otherwise set the customSecretRef field with a reference to you're own secret
##
authentication:
  defaultUser:
    enabled: true
  customSecretRef: secretref

## Specify an imagePullPolicy (Required)
## It's recommended to change this to 'Always' if the image tag is 'latest'
## ref: http://kubernetes.io/docs/user-guide/images/#updating-images
##
# imagePullPolicy: IfNotPresent
imagePullPolicy: Always

replicas: 1

## Persist data to a persistent volume
persistence:
  enabled: false
  testJournalPerformance: AUTO
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass:
  accessMode: ReadWriteOnce
  size: 8Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 512Mi
    cpu: 50m
  limits:
    memory: 512Mi
    cpu: 500m

brokerConfiguration:
  parameters:
    persistence-enabled: "true"
    journal-type: "ASYNCIO"
    paging-directory: "data/paging"
    bindings-directory: "data/bindings"
    journal-directory: "data/journal"
    large-messages-directory: "data/large-messages"
    critical-analyzer-timeout: "600000"
    security-enabled: "false"
    jmx-management-enabled: "true"
  addresses:
    'activemq.management#':
      dead-letter-address: "DLQ"
      expiry-address: "ExpiryQueue"
      redelivery-delay: "0"
      max-size-bytes: "-1"
      message-counter-history-day-limit: "10"
      address-full-policy: "PAGE"
      auto-create-queues: "true"
      auto-create-addresses: "true"
      auto-delete-queues: "true"
      auto-delete-addresses: "true"
    '#':
      dead-letter-address: "DLQ"
      expiry-address: "ExpiryQueue"
      max-size-bytes: "-1"
      message-counter-history-day-limit: "10"
      address-full-policy: "PAGE"
      max-delivery-attempts: "-1"
      max-redelivery-delay: "3600000"  # 1 hour
      redelivery-delay: "60000"  # 1 minute
      redelivery-delay-multiplier: "2"
      auto-create-queues: "true"
      auto-create-addresses: "true"
      auto-delete-queues: "true"
      auto-delete-addresses: "true"

## Install Default RBAC roles and bindings
rbac:
  install: false
  apiVersion: v1

ssl:
  enabled: true
