{{ if .Values.artemisCloud.enabled }}
apiVersion: broker.amq.io/v2alpha5
kind: ActiveMQArtemis
metadata:
  name: {{ .Release.Name }}
spec:
  deploymentPlan:
    size: 2
    image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:0.2.1
    persistenceEnabled: true
    messageMigration: true
    resources:
      requests:
        memory: {{ .Values.artemisCloud.resources.requests.memory }}
        cpu: {{ .Values.artemisCloud.resources.requests.cpu | quote }}
      limits:
        memory: {{ .Values.artemisCloud.resources.limits.memory }}
        cpu: {{ .Values.artemisCloud.resources.limits.cpu | quote }}
    storage:
      size: {{ .Values.artemisCloud.storage.size  | default "2Gi" }}
  acceptors:
  - name: jms
    protocols: jms
    port: 61617
    sslEnabled: true
    needClientAuth: true
    sslSecret: {{ .Release.Name }}-hdls-svc-jms-server-certs
    enabledProtocols: TLSv1.2
{{ end }}