{{ if .Values.httpdSidecar.enabled }}
{{- $paths := .Values.httpdSidecar.paths -}}

{{- $serverName := (print .Release.Name "." .Release.Namespace) }}
{{- if .Values.httpdSidecar.serverName }}
  {{- $serverName = tpl .Values.httpdSidecar.serverName . }}
{{ end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-apache
  labels:
    app: {{ .Release.Name }}
data:
  httpd.conf: |

    ServerRoot "/usr/local/apache2"
    ServerName {{ $serverName }}

    Listen 80
    PidFile /tmp/httpd.pid

    LoadModule mpm_event_module modules/mod_mpm_event.so
    LoadModule authn_file_module modules/mod_authn_file.so
    LoadModule authn_core_module modules/mod_authn_core.so
    LoadModule authz_host_module modules/mod_authz_host.so
    LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
    LoadModule authz_user_module modules/mod_authz_user.so
    LoadModule authz_core_module modules/mod_authz_core.so
    LoadModule access_compat_module modules/mod_access_compat.so
    LoadModule auth_basic_module modules/mod_auth_basic.so
    LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
    LoadModule reqtimeout_module modules/mod_reqtimeout.so
    LoadModule filter_module modules/mod_filter.so
    LoadModule mime_module modules/mod_mime.so
    LoadModule log_config_module modules/mod_log_config.so
    LoadModule env_module modules/mod_env.so
    LoadModule headers_module modules/mod_headers.so
    LoadModule setenvif_module modules/mod_setenvif.so
    LoadModule version_module modules/mod_version.so
    LoadModule proxy_module modules/mod_proxy.so
    LoadModule proxy_http_module modules/mod_proxy_http.so
    LoadModule proxy_ajp_module modules/mod_proxy_ajp.so
    LoadModule ssl_module modules/mod_ssl.so
    LoadModule unixd_module modules/mod_unixd.so
    LoadModule status_module modules/mod_status.so
    LoadModule autoindex_module modules/mod_autoindex.so
    LoadModule dir_module modules/mod_dir.so
    LoadModule alias_module modules/mod_alias.so
    LoadModule rewrite_module modules/mod_rewrite.so

    <IfModule unixd_module>
        User daemon
        Group daemon
    </IfModule>

    ServerAdmin you@example.com

    DocumentRoot "/usr/local/apache2/htdocs"
    <Directory "/usr/local/apache2/htdocs">
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    <IfModule dir_module>
        DirectoryIndex index.html
    </IfModule>

    <Files ".ht*">
        Require all denied
    </Files>

    ErrorLog /proc/self/fd/2

    LogLevel warn

    <IfModule log_config_module>
        LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
        LogFormat "%h %l %u %t \"%r\" %>s %b" common

        <IfModule logio_module>
          LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
        </IfModule>

        CustomLog /proc/self/fd/1 common

    </IfModule>

    <IfModule alias_module>

        ScriptAlias /cgi-bin/ "/usr/local/apache2/cgi-bin/"

    </IfModule>

    <Directory "/usr/local/apache2/cgi-bin">
        AllowOverride None
        Options None
        Require all granted
    </Directory>

    <IfModule headers_module>
        RequestHeader unset Proxy early
    </IfModule>

    <IfModule mime_module>
        TypesConfig conf/mime.types

        AddType application/x-compress .Z
        AddType application/x-gzip .gz .tgz
    </IfModule>

    Include conf/extra/vhosts.conf

    SSLPassPhraseDialog |/certs/server-key-password

    SSLSessionCache         shmcb:/var/cache/mod_ssl/scache(512000)
    SSLSessionCacheTimeout  300

    Mutex default

    SSLRandomSeed startup file:/dev/urandom  256
    SSLRandomSeed connect builtin

    SSLCryptoDevice builtin

  vhosts.conf: |

    <VirtualHost *:80>
        ServerName {{ $serverName }}

        <Location /server-status>
            SetHandler server-status
        </Location>

        {{ range .Values.httpdSidecar.paths }}
        {{- if (not .subpath | default false) }}
        Redirect permanent /{{ .name }} https://{{ $serverName }}/{{ .name }}
        {{- end -}}
        {{- end }}

    </VirtualHost>

    Listen 443

    <VirtualHost *:443>
        ServerName {{ $serverName }}
        ErrorLog /tmp/osp_error.log
        LogLevel warn

        <IfModule log_config_module>
            LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
            LogFormat "%h %l %u %t \"%r\" %>s %b" common
            <IfModule logio_module>
              LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
            </IfModule>
        </IfModule>

        CustomLog /tmp/osp_ssl_access.log combined

        SSLCertificateFile /certs/server.crt
        SSLCertificateKeyFile /certs/server.key
        SSLCACertificateFile /certs/root.crt

        SSLEngine on
        SSLProtocol -all +TLSv1.2 -TLSv1.3

        BrowserMatch "MSIE [2-6]" nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0
        BrowserMatch "MSIE [7-9]" ssl-unclean-shutdown

        RewriteEngine on

        RewriteCond %{QUERY_STRING} transport=websocket    [NC]

        <Directory />
            Options -Indexes
            AllowOverride all
            Order allow,deny
            allow from all
        </Directory>

        <IfModule mod_proxy_ajp.c>
            {{range .Values.httpdSidecar.paths }}
            {{ if (not .subpath | default false) -}}
            ProxyPass /{{ .name }} ajp://localhost:8009/{{ .name }}
            ProxyPassReverse /{{ .name }} /{{ .name }}
            {{ end -}}
            {{ end }}
        </IfModule>

        {{range .Values.httpdSidecar.paths }}
        {{ if .properties }}
        <Location /{{ .name }}>
        {{- .properties | nindent 10 }}
        </Location>
        {{- end }}
        {{- end }}

    </VirtualHost>
{{ end }}
