apiVersion: v1
kind: Secret
metadata:
  name: keystore-password
type: Opaque
data:
  keystore-password: {{ $secret := (lookup "v1" "Secret" .Release.Namespace "keystore-password") }}
    {{- if $secret -}}
      {{- index $secret "data" "keystore-password-test" -}}
    {{- else -}}
      {{- randAlphaNum 32 | b64enc | quote -}}
    {{- end -}}
