apiVersion: v1
kind: Secret 
metadata:
  name: {{ .Release.Name }}-keystore-password
type: Opaque
data:
  {{ .Release.Name }}-keystore-password: {{ $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-keystore-password" .Release.Name) }}
    {{- if $secret -}}
      {{- index $secret "data" "keystore-password" -}}
    {{- else -}}
      {{- randAlphaNum 32 | b64enc | quote -}}
    {{- end -}}
