{{- range .Values.certificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  secretName: {{ $.Release.Name }}-{{ .name }}
  duration: {{ .duration | default "8760h0m0s" }}
  renewBefore: {{ .renewBefore | default "720h0m0s" }}
  commonName: {{ .commonName }}
  privateKey:
    algorithm: RSA
    size: 2048
  {{- if .dnsNames }}
  dnsNames:
    {{- range .dnsNames }}
    - {{ . }}
    {{- end }}
  {{- end }}
  issuerRef:
    name: {{ if $.issuerRefName }}{{ $.issuerRefName }}{{ else }}{{ printf "%s-ca-issuer" $.Release.Namespace }}{{ end }}
    kind: {{ if $.issuerRefKind }}{{ $.issuerRefKind }}{{ else }}Issuer{{ end }}
  usages:
    - server auth
    - client auth
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: keystore-password
        key: password
  {{- if .isCA }}
  isCA: true
  {{- end }}
---
{{- end }}
