# SPDX-FileCopyrightText: Copyright Contributors to the GXF project
#
# SPDX-License-Identifier: Apache-2.0

{{- if (and .Values.ingress.enabled .Values.ingress.gate) -}}
apiVersion: gatemin.io/v1alpha1
kind: IngressGate
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations: {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  auth:
    type: NONE
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ tpl . $ }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  {{- range .Values.ingress.hosts }}
  host: {{ (tpl . $) }}
  services:
    {{- range $.Values.ingress.paths }}
    - path: {{ .path }}
      backend:
        serviceName: {{ $.Release.Name }}
        servicePort: 80
    {{- end }}
  {{- end }}
{{- end }}
