{{- if .Values.nodePorts }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-nodeport
  labels:
    app: {{ $.Release.Name }}-nodeport
spec:
  type: NodePort
  ports: 
  {{- range .Values.nodePorts }}
  - name: {{ $.Release.Name }}-{{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort | default .port }}
    protocol: {{ .protocol | default "TCP" }}
  {{- if .nodePort }}
    nodePort: {{ .nodePort }}
  {{- end }}
  {{- end }}

  selector:
    app: {{ $.Release.Name }}
{{- end }}
