{{- range $serviceName, $port := .Values.prometheusServices }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  annotations:
    prometheus.io/port: {{ $port | quote }}
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: {{ $.Release.Name }}
  ports:
    - protocol: TCP
      port: {{ $port }}
      targetPort: {{ $port }}
---
{{- end }}
