apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-probe-script
data:
  probe.sh: |
    #!/bin/bash
    PROBE_FAILED_FILE=/tmp/gxf_probe_failed
    ports=$(grep -sh "prometheus.port" /etc/osp/* | grep -v '^#' | cut -d '=' -f 2)
    rm -f $PROBE_FILE
    for port in $ports; do
      (curl -s -m 5 localhost:$port/metrics > /dev/null || touch $PROBE_FAILED_FILE) &
    done
    wait
    if [ -f $PROBE_FAILED_FILE ]; then
      exit 1
    fi

