apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
    - name: {{ .Release.Name }}
      port: {{ .Values.service.port }}
      {{- if .Values.httpdSidecar.enabled }}
      targetPort: https
      {{- else }}
      targetPort: http
      {{- end }}
      protocol: TCP
    {{- range .Values.extraServicePorts }}
    - name: {{ $.Release.Name }}-{{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}
