{{- $releaseName := .Release.Name -}}
{{- $servicePort := 80 -}}
{{- $targetPort := 8080 }}
{{- if .Values.service }}
  {{- $servicePort = .Values.service.port | default $servicePort }}
  {{- $targetPort = .Values.service.targetPort | default $targetPort }}
{{- else if .Values.httpdSidecar.enabled }}
  {{- $servicePort = 443 }}
  {{- $targetPort = 443 -}}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}
  labels:
    app: {{ $releaseName }}
spec:
  ports:
  - name: {{ $releaseName }}
    port: {{ $servicePort }}
    targetPort: {{ $targetPort | default $servicePort }}
    protocol: TCP
  {{- range .Values.extraServicePorts }}
  - name: {{ $releaseName }}-{{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort | default .port }}
    protocol: {{ .protocol | default "TCP" }}
  {{- end }}

  selector:
    app: {{ $releaseName }}
