apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    {{- if or .Values.httpdSidecar.enabled .Values.httpsConnector.enabled }}
    - name: https
      port: 443
      targetPort: https
    {{- end }}
    {{- range .Values.extraServicePorts }}
    - name: {{ $.Release.Name }}-{{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}
