apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-tomcat
data:
{{- if .Values.overrideTomcatConfig}}
  {{- range $name, $data := .Values.overrideTomcatConfig }}
  {{ $name }}: |
    {{- $data | nindent 4 }}
  {{- end }}
{{- else }}
{{- range $path, $_ := (.Files.Glob "config/tomcat/*") }}
  {{ trimPrefix "config/tomcat/" $path }}: |
    {{- tpl ($.Files.Get $path) $ | nindent 4 }}
{{- end }}
{{- end }}
