activemq-artemis:
  enabled: false
  persistence:
    enabled: true

artemisCloud:
  enabled: false

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 100m

  storage:
    size: 8Gi

imagePullPolicy: IfNotPresent

postgresql:
  enabled: false
  primary:
    extraPodSpec:
      enableServiceLinks: false
  readReplicas:
    extraPodSpec:
      enableServiceLinks: false

resources:
  limits:
    cpu: 4
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 1Gi

# extraEnv:
  # YOUR_ENV: your-value

# envFromSecrets:
  # YOUR_ENV:
    # secretName: your-secret
    # secretKey: your-secret-key

httpdSidecar:
  enabled: false

  image: httpd:2.4.52-alpine

  readinessProbe:
    httpGet:
      path: /
      port: 443
      scheme: HTTPS
    initialDelaySeconds: 30
    periodSeconds: 5
  livenessProbe:
    httpGet:
      path: /
      port: 443
      scheme: HTTPS
    initialDelaySeconds: 30
    periodSeconds: 5

pvcStorage:
  enabled: false

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  labels: {}
  path: /
  hosts:
    - hostname.ogsp.cloud
  ## Extra paths to prepend to every host configuration. This is useful when working with annotation based services.
  extraPaths: []
  # - path: /*
  #   backend:
  #     serviceName: ssl-redirect
  #     servicePort: use-annotation
  tls: []
  #  - secretName: wildcard-hostname-osgp-cloud
  #    hosts:
  #      - hostname.ogsp.cloud

logging:
  # rootLevel: WARN
  # Console logging is always enabled, file logging is optional
  toFileEnabled: false
  # Only used when fileEnabled=true
  # filename: your-own-choosing (defaults to .Release.Name)
  maxHistoryDays: 3
  totalSizeCap: 2GB
